project:
  name: quickstart-nvidia-clara
  shorten_stack_name: true
  regions:
    - us-west-2
tests:
  clara:
    template: ./templates/master.template.yaml
    parameters: 
      KeyName: $[taskcat_getkeypair]
      BastionKeyPairName: $[taskcat_getkeypair]
      AvailabilityZones: '$[taskcat_getaz_2]'
      QSS3BucketName: '$[taskcat_autobucket]'
      QSS3BucketRegion: $[taskcat_current_region]
      SourceCidrIP: 10.0.0.0/16
      BastionAccessCidr: 10.0.0.0/16
      
