project:
  name: quickstart-nvidia-imaging-clara-train
  shorten_stack_name: true
  regions:
    - us-east-1
    - us-west-2
    - ca-central-1
    - eu-west-1
    - eu-west-2
    - eu-central-1
    - ap-southeast-1
    - ap-southeast-2
tests:
  clara:
    template: ./templates/master.template.yaml
    parameters:
      KeyName: $[taskcat_getkeypair]
      BastionKeyPairName: $[taskcat_getkeypair]
      AvailabilityZones: '$[taskcat_getaz_2]'
      QSS3BucketName: '$[taskcat_autobucket]'
      QSS3BucketRegion: $[taskcat_current_region]
      SourceCidrIP: 10.0.0.0/16
      BastionAccessCidr: 10.0.0.0/16
      CertificateID: 'arn:aws:acm:us-west-2:377457852517:certificate/blahblah'
      UseHTTPS: HTTPS
    regions:
      - us-east-1
      - us-west-2
      - ca-central-1
      - eu-west-1
      - eu-west-2
      - eu-central-1
      - ap-southeast-1
      - ap-southeast-2
#  testHttpOnly:
#   template: ./templates/master.template.yaml
#   parameters:
#     KeyName: FakeKey
#     BastionKeyPairName: FakeKey
#     AvailabilityZones: '$[taskcat_getaz_2]'
#     QSS3BucketName: '$[taskcat_autobucket]'
#     QSS3BucketRegion: $[taskcat_current_region]
#     SourceCidrIP: 10.0.0.0/16
#     BastionAccessCidr: 10.0.0.0/16
#     CertificateID: ''
#     UseHTTPS: HTTP
#   regions:
#     - us-east-2
