Description: >

  This template deploys a deploys a highly available ECS cluster using an AutoScaling Group, with 
  ECS hosts distributed across multiple Availability Zones. Then, it deploys the Clara Train SDK 
  as an ECS services from containers published in the NVIDIA repository or Amazon EC2 Container 
  Registry (Amazon ECR)

  Last Modified: 3rd January 2020
  Author: Name <handle@amazon.com>

Parameters:
  EnvironmentName: 
    Description: Name of the CloudFormation stack
    Type: String
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  VPC:
    Description: VPC this ECS cluster should be deployed to
    Type: AWS::EC2::VPC::Id
  VPCCIDR:
    Description: CIDR for the VPC this ECS cluster should be deployed to
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Type: String
  PublicSubnet1ID:
    Description: ID of the public subnet 1
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2ID:
    Description: ID of the public subnet 2
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet1AID:
    Description: ID of the private subnet 1
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2AID:
    Description: ID of the private subnet 2
    Type: AWS::EC2::Subnet::Id
  Cmk:
    Description: An existing AWS KMS Customer Master Key (CMK) to encrypt file system. If left blank, an AWS service key will be used for encryption.
    Default: ''
    Type: String
  PerformanceMode:
    AllowedValues:
      - generalPurpose
      - maxIO
    Default: generalPurpose
    Description: Select the performance mode of the EFS file system.
    Type: String
  InstanceType:
    Description: Instance type for ECS hosts in cluster
    Type: String
    Default: p3.2xlarge
  ClusterSize:
    Description: Number of ECS hosts to deploy
    Type: Number
    Default: 1
  DesiredServiceCount:
    Description: Desired number of Clara service instances to run
    Type: Number
    Default: 1
  ContainerImageRegistry: 
    Description: Location of docker image or repository registry to pull
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: 'nvidia-clara-resources'
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), dots (.) and forward slash (/). The prefix should end with a forward slash (/).
    Default: 'quickstart-nvidia-clara/'
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), dots
      (.) and forward slash (/) and it should end with a forward slash (/).
    Type: String
  SourceCidrIP:
    Description: CIDR block from which connections to the load balancer will be accepted
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/0-32
    Type: String
  BastionSecurityGroupID: 
    Description: The Security Group of the bastion host, allowed to connect to private IPs of ECS hosts
    Type: AWS::EC2::SecurityGroup::Id

Conditions:
  GovCloudWestCondition: !Equals [ !Ref 'AWS::Region', us-gov-west-1]
  GovCloudEastCondition: !Equals [ !Ref 'AWS::Region', us-gov-east-1]

Resources:

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/efs.template.yaml
        - QSS3Region: !If [ GovCloudWestCondition, s3.us-gov-west-1, !If [ GovCloudEastCondition, s3.us-gov-east-1, s3 ] ]
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !Ref VPC
        VPCCIDR: !Ref VPCCIDR
        Subnets: !Join [",", [!Ref PrivateSubnet1AID, !Ref PrivateSubnet2AID]]
        Cmk: !Ref Cmk
        DeletionPolicy: Delete
        PerformanceMode: !Ref PerformanceMode

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/load-balancer.template.yaml
        - QSS3Region: !If [ GovCloudWestCondition, s3.us-gov-west-1, !If [ GovCloudEastCondition, s3.us-gov-east-1, s3 ] ]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPC: !Ref VPC
        Subnets: !Join [",", [!Ref PublicSubnet1ID, !Ref PublicSubnet2ID]]
        SourceCidrIP: !Ref SourceCidrIP

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/ecs-cluster.template.yaml
        - QSS3Region: !If [ GovCloudWestCondition, s3.us-gov-west-1, !If [ GovCloudEastCondition, s3.us-gov-east-1, s3 ] ]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        InstanceType: !Ref InstanceType
        ClusterSize: !Ref ClusterSize
        VPC: !Ref VPC
        Subnets: !Join [",", [!Ref PrivateSubnet1AID, !Ref PrivateSubnet2AID]]
        LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
        EFSSecurityGroup: !GetAtt EFS.Outputs.EFSSecurityGroup
        KeyName: !Ref KeyName
        BastionSecurityGroupID: !Ref BastionSecurityGroupID

  ClaraService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/service.template.yaml
        - QSS3Region: !If [ GovCloudWestCondition, s3.us-gov-west-1, !If [ GovCloudEastCondition, s3.us-gov-east-1, s3 ] ]
      Parameters:
        VPC: !Ref VPC
        Cluster: !GetAtt ECS.Outputs.Cluster
        DesiredCount: !Ref DesiredServiceCount
        Listener: !GetAtt ALB.Outputs.Listener
        Path: /
        ECSServiceAutoScalingRoleARN: !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        ElasticFileSystemDnsName: !GetAtt EFS.Outputs.ElasticFileSystemDnsName
        ContainerImageRegistry: !Ref ContainerImageRegistry

Outputs:

  ElasticFileSystemDnsName:
    Description: DNS name for the Amazon EFS file system.
    Value: !GetAtt EFS.Outputs.ElasticFileSystemDnsName

  ClaraServiceUrl:
    Description: The URL endpoint for the Clara Train service
    Value: !GetAtt ALB.Outputs.LoadBalancerUrl