Description: >
  This template deploys an Application Load Balancer that exposes the ECS services. (qs-1ql5cpbin)

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: The VPC the Application Load Balancer will be deployed to
  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  SourceCidrIP: 
    Description: CIDR block from which connections to the load balancer will be accepted
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/0-32
    Type: String
  CertificateID:
    Description: ARN for the Certificate to use for TLS
    Default: ''
    Type: String
  UseHTTPS:
    Description: Enable end-to-end encryption of connections to annotation server
    AllowedValues:
     - HTTPS
     - HTTP
    Default: HTTPS
    Type: String

Conditions:
  HTTPS:
    !Equals [ !Ref UseHTTPS, HTTPS ] 
  HTTP:
    !Equals [ !Ref UseHTTPS, HTTP ]

Mappings:
  Defaults:
    HTTPS:
      Port: 443
      Protocol: HTTPS
    HTTP:
      Port: 80
      Protocol: HTTP

Resources:
  # This security group defines who/where is allowed to access the Application Load Balancer.
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the load balancer that sits in front of ECS
      SecurityGroupIngress:
        # Allow access from anywhere to our ECS services
        - CidrIp: !Ref SourceCidrIP
          IpProtocol: tcp
          FromPort: !FindInMap [ Defaults, !Ref UseHTTPS, Port]
          ToPort: !FindInMap [ Defaults, !Ref UseHTTPS, Port]
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-LoadBalancers

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HTTP
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: !FindInMap [ Defaults, !Ref UseHTTPS, Port]
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup

  TLSLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HTTPS
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: !FindInMap [ Defaults, !Ref UseHTTPS, Port]
      Protocol: HTTPS
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
      Certificates:
        - CertificateArn: !Ref CertificateID

  # We define a default target group here, as this is a mandatory Parameters
  # when creating an Application Load Balancer Listener. This is not used, instead
  # a target group is created per-service in each service template (../services/*)
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: !FindInMap [ Defaults, !Ref UseHTTPS, Port]
      Protocol: !FindInMap [ Defaults, !Ref UseHTTPS, Protocol]
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

Outputs:
  LoadBalancerSecurityGroup:
    Description: Security group that defines access to the Application Load Balancer.
    Value: !Ref LoadBalancerSecurityGroup

  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName

  Listener:
    Description: A reference to a port 80 listener
    Value: !If [HTTP, !Ref LoadBalancerListener, !Ref TLSLoadBalancerListener]

