Description: >

  This template deploys a VPC, with a pair of public and private subnets  
  across two Availability Zones. It deploys an Internet Gateway, with a default 
  route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ), 
  and corresponding default routes in the private subnets.

  It then deploys a bastion host to access private subnets, and an EFS to share
  and persist data across multiple container instances.

  Finally, it deploys the Clara Train SDK as a service on 
  a highly available ECS cluster, with an AutoScaling Group distributed across
  two Availability Zones. 

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC network configuration
        Parameters:
        - AvailabilityZones
        - VPCCIDR
        - PrivateSubnet1CIDR
        - PrivateSubnet2CIDR
        - PublicSubnet1CIDR
        - PublicSubnet2CIDR
      - Label:
          default: Linux bastion configuration
        Parameters:
        - BastionKeyPairName
        - BastionAccessCidr
      - Label:
          default: EFS configuration
        Parameters:
        - EFSDeletionPolicy
        - PerformanceMode
      - Label:
          default: ECS EC2 configuration
        Parameters:
        - KeyName
        - ECSHostInstanceType
      - Label:
          default: ECS cluster configuration
        Parameters:
        - SourceCidrIP
        - CertificateID
        - UseHTTPS
        - ClusterSize
        - DesiredServiceCount
      - Label:
          default: AWS Quick Start configuration
        Parameters:      
        - QSS3BucketName
        - QSS3KeyPrefix
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      VPCCIDR:
        default: VPC CIDR
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      BastionKeyPairName:
        default: Bastion key pair name
      BastionAccessCidr:
        default: Allowed bastion external access CIDR 
      EFSDeletionPolicy:
        default: EFS deletion policy
      PerformanceMode:
        default: EFS performance mode
      KeyName:
        default: ECS EC2 key pair name
      ECSHostInstanceType:
        default: ECS EC2 instance type
      SourceCidrIP: 
        default: Allowed load balancer external access CIDR 
      UseHTTPS:
        default: Enable end-to-end encryption of connections to the AI-Assisted Annotation service
      CertificateID:
        default: ARN for the ACM Certificate to use for TLS. Leave blank for HTTP connections
      ClusterSize:
        default: Number of ECS hosts
      DesiredServiceCount:
        default: Number of instances of this Clara Train task
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.180.0.0/16
    Description: CIDR Block for the VPC.
    Type: String
  AvailabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC. Note: The logical order is preserved and only 2 AZs are used for this deployment.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.180.24.0/21
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.180.32.0/21
    Description: CIDR block for private subnet 2 located in Availability Zone 2.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.180.8.0/21
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone 1.
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.180.16.0/21
    Description: CIDR Block for the public DMZ subnet 2 located in Availability Zone 2.
    Type: String
  EFSDeletionPolicy:
    AllowedValues:
      - Delete
      - Retain
    Default: Delete
    Description: Retain or delete the Amazon EFS resources after CloudFormation stack deletion.
    Type: String
  PerformanceMode:
    AllowedValues:
      - generalPurpose
      - maxIO
    Default: generalPurpose
    Description: Select performance mode of EFS file system.
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), dots (.) and forward slash (/). The prefix should end with a forward slash (/).
    Default: quickstart-nvidia-clara/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), dots
      (.) and forward slash (/) and it should end with a forward slash (/).
    Type: String
  ECSHostInstanceType:
    Description: Instance type for the ECS hosts
    Type: String
    Default: p3.2xlarge
    AllowedValues:
    - p3.2xlarge
    - p3.8xlarge
    - p3.16xlarge
    - p3dn.24xlarge
  ClusterSize:
    Description: Number of ECS hosts
    Type: String
    AllowedPattern: ^\d+$
    Default: 1
  DesiredServiceCount:
    Description: Number of Clara service instances
    Type: String
    AllowedPattern: ^\d+$
    Default: 1
  SourceCidrIP: 
    Description: CIDR block from which connections to the load balancer will be accepted.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/0-32
    Type: String
  BastionKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to Bastion Host.
    ConstraintDescription: Must be the name of an existing EC2 Key Pair
  BastionAccessCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: CIDR block from which connections to the bastion host will be accepted.
    Type: String
  CertificateID:
    Description: ARN for the Certificate to use for TLS
    Default: ''
    Type: String
  UseHTTPS:
    Description: Enable end-to-end encryption of connections to annotation server
    AllowedValues:
     - HTTPS
     - HTTP
    Default: HTTPS
    Type: String  

Mappings:
  Defaults:
    Bastion:
      InstanceType: t2.medium
    Clara:
      Uri: nvcr.io/nvidia/clara-train-sdk:v2.0

Conditions:
  GovCloudWestCondition: !Equals [ !Ref 'AWS::Region', us-gov-west-1]
  GovCloudEastCondition: !Equals [ !Ref 'AWS::Region', us-gov-east-1]

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
        - QSS3Region: !If [ GovCloudWestCondition, s3.us-gov-west-1, !If [ GovCloudEastCondition, s3.us-gov-east-1, s3 ] ]
      Parameters:
        AvailabilityZones: !Join [",", !Ref AvailabilityZones]
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        VPCCIDR: !Ref VPCCIDR

  Bastion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 
      - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template
      - QSS3Region: !If [ GovCloudWestCondition, s3.us-gov-west-1, !If [ GovCloudEastCondition, s3.us-gov-east-1, s3 ] ]
      Parameters:
        BastionInstanceType: !FindInMap [ Defaults, Bastion, InstanceType ]
        KeyPairName: !Ref BastionKeyPairName
        RemoteAccessCIDR: !Ref BastionAccessCidr
        PublicSubnet1ID: !GetAtt VPC.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPC.Outputs.PublicSubnet2ID
        VPCID: !GetAtt VPC.Outputs.VPCID

  ClaraCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/clara-cluster.template.yaml
        - QSS3Region: !If [ GovCloudWestCondition, s3.us-gov-west-1, !If [ GovCloudEastCondition, s3.us-gov-east-1, s3 ] ]
      Parameters:
        KeyName: !Ref KeyName
        VPC: !GetAtt VPC.Outputs.VPCID
        VPCCIDR: !Ref VPCCIDR
        PublicSubnet1ID: !GetAtt VPC.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPC.Outputs.PublicSubnet2ID
        PrivateSubnet1AID: !GetAtt VPC.Outputs.PrivateSubnet1AID
        PrivateSubnet2AID: !GetAtt VPC.Outputs.PrivateSubnet2AID
        ECSHostInstanceType: !Ref ECSHostInstanceType
        ClusterSize: !Ref ClusterSize
        DesiredServiceCount: !Ref DesiredServiceCount
        ContainerImageRegistry: !FindInMap [ Defaults, Clara, Uri ]
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        SourceCidrIP: !Ref SourceCidrIP
        BastionSecurityGroupID: !GetAtt Bastion.Outputs.BastionSecurityGroupID
        PerformanceMode: !Ref PerformanceMode
        EFSDeletionPolicy: !Ref EFSDeletionPolicy
        CertificateID: !Ref CertificateID
        UseHTTPS: !Ref UseHTTPS

Outputs:
  ClaraServiceUrl:
    Description: The URL endpoint for the Clara Train service
    Value: !Sub ${ClaraCluster.Outputs.ClaraServiceUrl}/

  ElasticFileSystemDnsName:
    Description: DNS name for the Amazon EFS file system.
    Value: !GetAtt ClaraCluster.Outputs.ElasticFileSystemDnsName